# Generated by Django 5.2.17 on 2026-10-03 09:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('unknown', 'Desconhecido'), ('suspicious', 'Suspeito'), ('blacklisted', 'Blacklist'), ('cleared', 'Limpo')], default='unknown', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('phishing', 'Phishing'), ('sim_swap', 'SIM swap'), ('fake_prize', 'Falso prémio'), ('impersonation', 'Falsa identidade'), ('loan_scam', 'Falso empréstimo'), ('other', 'Outro')], max_length=20, null=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('classification_count', models.PositiveIntegerField(default=0)),
                ('fraud_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('phishing', 'Phishing'), ('sim_swap', 'SIM swap'), ('fake_prize', 'Falso prémio'), ('impersonation', 'Falsa identidade'), ('loan_scam', 'Falso empréstimo'), ('other', 'Outro')], default='other', max_length=20)),
                ('behavior', models.TextField()),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('call', 'Chamada'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Outro')], default='other', max_length=20)),
                ('amount_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reporter_contact', models.CharField(blank=True, max_length=100)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('moderation_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reputation.phonenumber')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('verdict', models.CharField(choices=[('safe', 'Seguro'), ('suspicious', 'Suspeito'), ('fraud', 'Fraude')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('phishing', 'Phishing'), ('sim_swap', 'SIM swap'), ('fake_prize', 'Falso prémio'), ('impersonation', 'Falsa identidade'), ('loan_scam', 'Falso empréstimo'), ('other', 'Outro')], max_length=20, null=True)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('explanation', models.TextField(blank=True)),
                ('provider', models.CharField(max_length=50)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='reputation.phonenumber')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['status', 'category'], name='reputation__status_555296_idx'),
        ),
        migrations.AddIndex(
            model_name='numberreport',
            index=models.Index(fields=['status'], name='reputation__status_3a3810_idx'),
        ),
    ]
