# Generated by Django 5.2.17 on 2026-10-03 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostDocumentOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('document_type', models.CharField(choices=[('bi', 'Bilhete de identidade'), ('passport', 'Passaporte'), ('driving_license', 'Carta de condução'), ('dire', 'DIRE'), ('other', 'Outro')], max_length=30)),
                ('document_number', models.CharField(db_index=True, max_length=50)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_contact', models.CharField(blank=True, max_length=100)),
                ('lost_at', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('found', 'Encontrado'), ('closed', 'Fechada')], default='open', max_length=20)),
                ('station_name', models.CharField(max_length=200)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['document_type', 'document_number'], name='occurrences_documen_5ba8e0_idx'), models.Index(fields=['status'], name='occurrences_status_ac3ca9_idx')],
            },
        ),
    ]
